### ISSUE TITLE
Notice: Undefined offset: 1 in /vendor/hansott/pinterest-php/src/Pinterest/Http/BuzzClient.php on line 71

### ISSUE THREAD

**Issue by PavithraHari** [hansott/pinterest-php#21] opened 2017-12-15 07:49 UTC
Hi,
I am also facing the same issue
I have installed the PHP Pinterest API on my server and I have authenticated the user using OAuth. When I am trying to get board details I am facing an issue "Notice: Undefined offset: 1 in /vendor/hansott/pinterest-php/src/Pinterest/Http/BuzzClient.php on line 71". I have debugged the issue and found that the key "Pinterest-Generated-By" doesn't have the value. For this please refer Line number 71 in /vendor/hansott/pinterest-php/src/Pinterest/Http/BuzzClient.php

Line cauisng issue,

list($key, $value) = explode(': ', $header);

My code:

$client = new Pinterest\Http\BuzzClient();

$auth = Pinterest\Authentication::onlyAccessToken($client, $token);
$api = new Pinterest\Api($auth);

$response = $api->getUserBoards();
Please let me know why I am facing this issue. And do I need to add value in settings to get the value for "Pinterest-Generated-By"?

Thanks

**Comment by hansott** [comment] 2017-12-19 09:37
duplicate of #20

**Closed as completed by hansott** 2017-12-19 09:37 UTC
Labels: duplicate
